import { Metadata } from "next";
import { Sarabun } from "next/font/google";
import { UserProvider } from "./context/UserContext";
import "./globals.css";
import TopNav from "./ui/TopNav";

const sarabun = Sarabun({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "600"],
});

export const metadata: Metadata = {
  title: "BB Pragan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${sarabun.className} min-h-screen bg-gray-100`}>
        <UserProvider>
          <TopNav />
          <main className="p-8">{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
