import { Metadata } from "next";
import { Sarabun } from "next/font/google";
import { UserProvider } from "./context/UserContext";
import "./globals.css";
import BottomBar from "./ui/BottomBar";

const sarabun = Sarabun({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "600"],
});

export const metadata: Metadata = {
  title: "BB Pragun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${sarabun.className} min-h-screen bg-gray-100`}>
        <UserProvider>
          <main className="p-8">{children}</main>
          <BottomBar />
        </UserProvider>
      </body>
    </html>
  );
}
