import Image from "next/image";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div>
        <h1 className="text-4xl font-bold">BB Pragan</h1>
        <p className="text-lg">Generated by create next app</p>
      </div>
    </main>
  );
}
